version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - db_data:/var/lib/mysql

  php-fpm:
    container_name: php-fpm
    build:
      context: delivery
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/symfony_docker
    depends_on:
      - mysql

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8083:83'
    volumes:
      - .:/var/www/symfony_docker:rw
      - ./delivery/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - mysql

volumes:
  db_data:
